apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-deployment-volume-claim
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
