apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-deployment-volume
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: normal
  hostPath:
    path: /var/opt/logs/hello-deployment-volume
