apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox-ingress
  namespace: monitoring
  labels:
    name: sandbox-ingress
  annotations:
    kubernetes.io/ingress.class: monitoring-ingress
spec:
  tls:
    - hosts:
        - grafana.local
      secretName: cert-grafana
  rules:
    - host: prometheus.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-operated
                port:
                  number: 9090

    - host: grafana.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-grafana
                port:
                  number: 80
