apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-deployment-volume-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
