apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-deployment-volume
  namespace: hello-deployment
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /tmp/hello-deployment-volume/
