apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lounge-volume-claim
  namespace: lounge-irc
spec:
  volumeMode: Filesystem
  storageClassName: normal
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
