apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-14.11.0
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-server-np
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: prometheus
  type: NodePort
status:
  loadBalancer: {}
