kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: nextcloud
  name: nextcloud-database-policy
spec:
  podSelector:
    matchLabels: {}
  ingress:
    - from:
      - podSelector: {}
