apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-database-volume-claim
  namespace: nextcloud
spec:
  volumeMode: Filesystem
  storageClassName: normal
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
