apiVersion: v1
kind: PersistentVolume
metadata:
  name: lounge-deployment-volume
  namespace: lounge-irc
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: normal
  hostPath:
    path: /tmp/lounge-deployment/
