apiVersion: v1
kind: Service
metadata:
  name: lounge-irc-service
  namespace: lounge-irc
spec:
  selector:
    run: lounge-irc
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 5000
  type: NodePort
