apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-database-deployment-volume
  namespace: nextcloud
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: normal
  hostPath:
    path: /tmp/nextcloud-database-deployment/
