apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-config-volume
  labels:
    app: app
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /tmp/syncthing-config-volume


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-data-volume
  labels:
    app: app
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /tmp/syncthing-data-volume
