apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config-claim
  namespace: syncthing
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-volume-claim
  namespace: syncthing
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
